print( "Loading heilong Ctrl.lua" )

function config(map)
	MapCanSavePos(map, 0)		-- 1 = Allow players to save respaw // 0 = Do not allow players to save respaw
	MapCanPK(map, 1)			-- 1 = Turns on PK Mouse Sword Icon // 0 = Turns off PK Mouse Sword Icon ( Need to press CTRL key )
	MapCopyNum(map, 1)			-- 1 Copy of the map will be generated by GameServer
	MapCanStall(map , 0)
	SingleMapCopyPlyNum(map, 300)	-- 300 Players are allowed to enter the map
	MapCanTeam(map , 1)			-- 1 = Allow players to create party // 0 = Do not allow players to create party
	MapType ( map , 4 )			-- 0 = PvP Off // 1 = PvP Off // 2 = PvP On ( Not allowed to kill Guild and Party Mates ) // 3 = PvP On ( Allowed to kill any player but not Party Mates ) // 4 = PvP On ( Not allowed to kill Guild and Party Mates )        
end

function map_copy_run_special_heilong()
end
function after_enter_heilong( role , map_copy )
--AfterEnter(role)
end
function before_leave_heilong( role )
end
function map_run_heilong( map )
end
function map_copy_run_heilong (map_copy)
end

function get_map_entry_pos_heilong()
	local POS_X = 3430
	local POS_Y = 3296
	return POS_X , POS_Y
end

function init_entry(map)
	SetMapEntryMapName(map, "darkblue")
	--SetMapEntryTime(map, "2008/8/30/18/40", "1/0/0", "0/0/30", "0/0/35")
	 SetMapEntryTime(map, "2010/01/01/21/0", "1/0/0", "0/3/0", "0/3/0") 
	 		-- Карта, на которой установлена точка входа на эту карту
											-- Установка времени работы карты
											-- 2010/01/01/5/0 (год/месяц/день/часы/минуты) - время начала работы карты
											-- 0/1/0  (день/час/минута) - время открытия портала (открываем ежечасно)
											-- 0/0/30 (день/час/минута) - время работы портала (портал работает 30 минут)
											-- 0/0/55 (день/час/минута) - время работы карты (карта работает 55 минут)
end